/*
 *
 * Editor constants
 *
 */

enum ActionTypes {
  DEFAULT_ACTION = 'app/Editor/DEFAULT_ACTION',
  CREATE_SLIDESHOW = 'app/Editor/CREATE_SLIDESHOW',
  CREATE_SLIDESHOW_SUCCESS = 'app/Editor/CREATE_SLIDESHOW_SUCCESS',
  CREATE_SLIDESHOW_FAILURE = 'app/Editor/CREATE_SLIDESHOW_FAILURE',
  CREATE_SLIDE = 'app/Editor/CREATE_SLIDE',
  CREATE_SLIDE_SUCCESS = 'app/Editor/CREATE_SLIDE_SUCCESS',
  CREATE_SLIDE_FAILURE = 'app/Editor/CREATE_SLIDE_FAILURE',
  REMOVE_SLIDE = 'app/Editor/REMOVE_SLIDE',
}

export default ActionTypes;
