/*
 *
 * Editor constants
 *
 */

enum ActionTypes {
  DEFAULT_ACTION = 'app/Editor/DEFAULT_ACTION',
  CREATE_SLIDESHOW = 'app/Editor/CREATE_SLIDESHOW',
  CREATE_SLIDESHOW_SUCCESS = 'app/Editor/CREATE_SLIDESHOW_SUCCESS',
  CREATE_SLIDESHOW_FAILURE = 'app/Editor/CREATE_SLIDESHOW_FAILURE',
  CREATE_ANNOTATION = 'app/Editor/CREATE_ANNOTATION',
  SET_MAP = 'app/Editor/SET_MAP',
  REMOVE_ANNOTATION = 'app/Editor/REMOVE_ANNOTATION',
  EDIT_ANNOTATION = 'app/Editor/EDIT_ANNOTATION',
  CHANGE_ORDER = 'app/Editor/CHANGE_ORDER',
}

export default ActionTypes;
