/*
 *
 * HomePage constants
 *
 */

enum ActionTypes {
  LOAD_SLIDESHOWS = 'app/HomePage/LOAD_SLIDESHOWS',
  CREATE_SLIDESHOW = 'app/HomePage/CREATE_SLIDESHOW',
  CREATE_SLIDESHOW_SUCCESS = 'app/HomePage/CREATE_SLIDESHOW_SUCCESS',
  CREATE_SLIDESHOW_FAILURE = 'app/HomePage/CREATE_SLIDESHOW_FAILURE',
  REMOVE_SLIDESHOW = 'app/HomePage/REMOVE_SLIDESHOW',
  REMOVE_SLIDESHOW_SUCCESS = 'app/HomePage/REMOVE_SLIDESHOW_SUCCESS',
  REMOVE_SLIDESHOW_FAILURE = 'app/HomePage/REMOVE_SLIDESHOW_FAILURE',
  SLIDESHOW_DUPLICATE = 'app/HomePage/SLIDESHOW_DUPLICATE',
}

export default ActionTypes;
