/*
 *
 * App constants
 *
 */

enum ActionTypes {
  SET_PROGRESS = 'app/App/SET_PROGRESS',
  EXPORT_START = 'app/App/EXPORT_START',
  EXPORT_SUCCESS = 'app/App/EXPORT_SUCCESS',
  EXPORT_FAILURE = 'app/App/EXPORT_FAILURE',
  IMPORT_SLIDESHOW = 'app/App/IMPORT_SLIDESHOW',
  IMPORT_SLIDESHOW_SUCCESS = 'app/App/IMPORT_SLIDESHOW_SUCCESS',
  IMPORT_SLIDESHOW_FAILURE = 'app/App/IMPORT_SLIDESHOW_FAILURE',
}

export default ActionTypes;
